/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TaskExecLog struct {
	Log string `json:"log,omitempty"`
	TaskId string `json:"taskId,omitempty"`
	CreatedTime int64 `json:"createdTime,omitempty"`
}
