/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RerunWorkflowRequest struct {
	ReRunFromWorkflowId string `json:"reRunFromWorkflowId,omitempty"`
	WorkflowInput map[string]interface{} `json:"workflowInput,omitempty"`
	ReRunFromTaskId string `json:"reRunFromTaskId,omitempty"`
	TaskInput map[string]interface{} `json:"taskInput,omitempty"`
	CorrelationId string `json:"correlationId,omitempty"`
}
