/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SkipTaskRequest struct {
	TaskInput map[string]interface{} `json:"taskInput,omitempty"`
	TaskOutput map[string]interface{} `json:"taskOutput,omitempty"`
}
