/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EventHandler struct {
	Name string `json:"name"`
	Event string `json:"event"`
	Condition string `json:"condition,omitempty"`
	Actions []Action `json:"actions"`
	Active bool `json:"active,omitempty"`
	EvaluatorType string `json:"evaluatorType,omitempty"`
}
