/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TaskDetails struct {
	WorkflowId string `json:"workflowId,omitempty"`
	TaskRefName string `json:"taskRefName,omitempty"`
	Output map[string]interface{} `json:"output,omitempty"`
	TaskId string `json:"taskId,omitempty"`
}
