/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Health struct {
	Details map[string]interface{} `json:"details,omitempty"`
	ErrorMessage string `json:"errorMessage,omitempty"`
	Healthy bool `json:"healthy,omitempty"`
}
