/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PollData struct {
	QueueName string `json:"queueName,omitempty"`
	Domain string `json:"domain,omitempty"`
	WorkerId string `json:"workerId,omitempty"`
	LastPollTime int64 `json:"lastPollTime,omitempty"`
}
