/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SubWorkflowParams struct {
	Name string `json:"name"`
	Version int32 `json:"version,omitempty"`
	TaskToDomain map[string]string `json:"taskToDomain,omitempty"`
	WorkflowDefinition *WorkflowDef `json:"workflowDefinition,omitempty"`
}
