/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StartWorkflow struct {
	Name string `json:"name,omitempty"`
	Version int32 `json:"version,omitempty"`
	CorrelationId string `json:"correlationId,omitempty"`
	Input map[string]interface{} `json:"input,omitempty"`
	TaskToDomain map[string]string `json:"taskToDomain,omitempty"`
}
