/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BulkResponse struct {
	BulkErrorResults map[string]string `json:"bulkErrorResults,omitempty"`
	BulkSuccessfulResults []string `json:"bulkSuccessfulResults,omitempty"`
}
