/*
 * OpenAPI definition
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Action struct {
	Action string `json:"action,omitempty"`
	StartWorkflow *StartWorkflow `json:"start_workflow,omitempty"`
	CompleteTask *TaskDetails `json:"complete_task,omitempty"`
	FailTask *TaskDetails `json:"fail_task,omitempty"`
	ExpandInlineJSON bool `json:"expandInlineJSON,omitempty"`
}
