/*
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type ExtendedWorkflowDef struct {
	BusinessStateSchema           map[string]map[string]interface{} `json:"businessStateSchema,omitempty"`
	CreateTime                    int64                             `json:"createTime,omitempty"`
	CreatedBy                     string                            `json:"createdBy,omitempty"`
	Description                   string                            `json:"description,omitempty"`
	FailureWorkflow               string                            `json:"failureWorkflow,omitempty"`
	InputParameters               []string                          `json:"inputParameters,omitempty"`
	InputTemplate                 map[string]interface{}            `json:"inputTemplate,omitempty"`
	Name                          string                            `json:"name"`
	OnStateChange                 map[string][]StateChangeEvent     `json:"onStateChange,omitempty"`
	OutputParameters              map[string]interface{}            `json:"outputParameters,omitempty"`
	OverwriteTags                 bool                              `json:"overwriteTags,omitempty"`
	OwnerApp                      string                            `json:"ownerApp,omitempty"`
	OwnerEmail                    string                            `json:"ownerEmail,omitempty"`
	Restartable                   bool                              `json:"restartable,omitempty"`
	SchemaVersion                 int32                             `json:"schemaVersion,omitempty"`
	Tags                          []TagObject                       `json:"tags,omitempty"`
	Tasks                         []WorkflowTask                    `json:"tasks"`
	TimeoutPolicy                 string                            `json:"timeoutPolicy,omitempty"`
	TimeoutSeconds                int64                             `json:"timeoutSeconds"`
	UpdateTime                    int64                             `json:"updateTime,omitempty"`
	UpdatedBy                     string                            `json:"updatedBy,omitempty"`
	Variables                     map[string]interface{}            `json:"variables,omitempty"`
	Version                       int32                             `json:"version,omitempty"`
	WorkflowStatusListenerEnabled bool                              `json:"workflowStatusListenerEnabled,omitempty"`
	WorkflowStatusListenerSink    string                            `json:"workflowStatusListenerSink,omitempty"`
}
