/*
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type ExtendedTaskDef struct {
	BackoffScaleFactor          int32                  `json:"backoffScaleFactor,omitempty"`
	BaseType                    string                 `json:"baseType,omitempty"`
	ConcurrentExecLimit         int32                  `json:"concurrentExecLimit,omitempty"`
	CreateTime                  int64                  `json:"createTime,omitempty"`
	CreatedBy                   string                 `json:"createdBy,omitempty"`
	Description                 string                 `json:"description,omitempty"`
	ExecutionNameSpace          string                 `json:"executionNameSpace,omitempty"`
	InputKeys                   []string               `json:"inputKeys,omitempty"`
	InputTemplate               map[string]interface{} `json:"inputTemplate,omitempty"`
	IsolationGroupId            string                 `json:"isolationGroupId,omitempty"`
	Name                        string                 `json:"name"`
	OutputKeys                  []string               `json:"outputKeys,omitempty"`
	OverwriteTags               bool                   `json:"overwriteTags,omitempty"`
	OwnerApp                    string                 `json:"ownerApp,omitempty"`
	OwnerEmail                  string                 `json:"ownerEmail,omitempty"`
	PollTimeoutSeconds          int32                  `json:"pollTimeoutSeconds,omitempty"`
	RateLimitFrequencyInSeconds int32                  `json:"rateLimitFrequencyInSeconds,omitempty"`
	RateLimitPerFrequency       int32                  `json:"rateLimitPerFrequency,omitempty"`
	ResponseTimeoutSeconds      int64                  `json:"responseTimeoutSeconds,omitempty"`
	RetryCount                  int32                  `json:"retryCount,omitempty"`
	RetryDelaySeconds           int32                  `json:"retryDelaySeconds,omitempty"`
	RetryLogic                  string                 `json:"retryLogic,omitempty"`
	Tags                        []TagObject            `json:"tags,omitempty"`
	TimeoutPolicy               string                 `json:"timeoutPolicy,omitempty"`
	TimeoutSeconds              int64                  `json:"timeoutSeconds"`
	UpdateTime                  int64                  `json:"updateTime,omitempty"`
	UpdatedBy                   string                 `json:"updatedBy,omitempty"`
}
