/*
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type StateChangeEvent struct {
	Payload map[string]interface{} `json:"payload,omitempty"`
	Type_   string                 `json:"type"`
}
