/*
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type TagObject struct {
	Key   string       `json:"key,omitempty"`
	Type_ string       `json:"type,omitempty"`
	Value *interface{} `json:"value,omitempty"`
}

func NewTagObject(metadataTag MetadataTag) TagObject {
	var value interface{} = metadataTag.Value

	return TagObject{
		Key:   metadataTag.Key,
		Value: &value,
	}
}
