/*
 * Orkes Conductor API Server
 *
 * Orkes Conductor API Server
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

type TagObject struct {
	Key   string `json:"key,omitempty"`
	Type_ string `json:"type,omitempty"`
	Value string `json:"value,omitempty"`
}

func NewTagObject(metadataTag MetadataTag) TagObject {
	var value string = metadataTag.Value

	return TagObject{
		Key:   metadataTag.Key,
		Type_: "METADATA",
		Value: value,
	}
}
